# This file contains the configuration settings for your Redwood app.
# This file is also what makes your Redwood app a Redwood app.
# If you remove it and try to run `yarn rw dev`, you'll get an error.
#
# For the full list of options, see the "App Configuration: redwood.toml" doc:
# https://redwoodjs.com/docs/app-configuration-redwood-toml

[web]
  bundler = "vite"
  title = "Redwood App"
  port = "${WEB_DEV_PORT:8910}"
  host = "local.spoonjoy.app"
  apiUrl = "/.redwood/functions" # You can customize graphql and dbauth urls individually too: see https://redwoodjs.com/docs/app-configuration-redwood-toml#api-paths
  includeEnvironmentVariables = ["RWJS_API_URL", "APPLE_CLIENT_ID", "GITHUB_CLIENT_ID", "GOOGLE_CLIENT_ID"]
[api]
  port = "${API_DEV_PORT:8911}"
[browser]
  open = true
